// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:flutter_view_controller/models/view_abstract_api.dart'
    as prefix0;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.GenericClassMirrorImpl(
            r'ViewAbstractApi',
            r'.ViewAbstractApi',
            519,
            0,
            const prefix0.Reflector(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 0,
              r'toString': 1,
              r'noSuchMethod': 0,
              r'hashCode': 1,
              r'runtimeType': 1,
              r'getFieldIcon': 4,
              r'getIcon': 0,
              r'getColor': 0,
              r'getCardTrailing': 0,
              r'getCardLeading': 0,
              r'getCardLeadingImage': 0,
              r'getCardLeadingImageProvider': 0,
              r'getSubtitleHeaderText': 0,
              r'getSubtitleHeaderTextOnly': 0,
              r'getHeaderText': 0,
              r'getHeaderTextOnly': 0,
              r'getLabelText': 0,
              r'getLabelTextOnly': 0,
              r'getAppBarActionsEdit': 0,
              r'getAppBarActionsView': 0,
              r'getPopupActionsList': 0,
              r'getInstanceMirror': 1,
              r'getFieldValue': 0,
              r'setFieldValue': 4,
              r'iD': 1,
              r'iD=': 0,
              r'getCustomAction': 1,
              r'requireObjects': 1,
              r'requireObjectsList': 1,
              r'getBodyExtenstionParams': 1,
              r'getBodyCurrentActionASC': 0,
              r'getBody': 0,
              r'getHeadersExtenstion': 1,
              r'getHeaders': 1,
              r'getRespones': 2,
              r'viewCall': 3,
              r'addCall': 2,
              r'listCall': 4,
              r'getHttp': 1,
              r'getBodyCurrentAction': 0
            },
            (o) => false,
            null,
            0),
        r.TypeVariableMirrorImpl(
            r'T', r'.ViewAbstractApi.T', const prefix0.Reflector(), -1, 0, null)
      ],
      null,
      null,
      <Type>[prefix0.ViewAbstractApi],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getFieldIcon': (dynamic instance) => instance.getFieldIcon,
        r'getIcon': (dynamic instance) => instance.getIcon,
        r'getColor': (dynamic instance) => instance.getColor,
        r'getCardTrailing': (dynamic instance) => instance.getCardTrailing,
        r'getCardLeading': (dynamic instance) => instance.getCardLeading,
        r'getCardLeadingImage': (dynamic instance) =>
            instance.getCardLeadingImage,
        r'getCardLeadingImageProvider': (dynamic instance) =>
            instance.getCardLeadingImageProvider,
        r'getSubtitleHeaderText': (dynamic instance) =>
            instance.getSubtitleHeaderText,
        r'getSubtitleHeaderTextOnly': (dynamic instance) =>
            instance.getSubtitleHeaderTextOnly,
        r'getHeaderText': (dynamic instance) => instance.getHeaderText,
        r'getHeaderTextOnly': (dynamic instance) => instance.getHeaderTextOnly,
        r'getLabelText': (dynamic instance) => instance.getLabelText,
        r'getLabelTextOnly': (dynamic instance) => instance.getLabelTextOnly,
        r'getAppBarActionsEdit': (dynamic instance) =>
            instance.getAppBarActionsEdit,
        r'getAppBarActionsView': (dynamic instance) =>
            instance.getAppBarActionsView,
        r'getPopupActionsList': (dynamic instance) =>
            instance.getPopupActionsList,
        r'getInstanceMirror': (dynamic instance) => instance.getInstanceMirror,
        r'getFieldValue': (dynamic instance) => instance.getFieldValue,
        r'setFieldValue': (dynamic instance) => instance.setFieldValue,
        r'iD': (dynamic instance) => instance.iD,
        r'getCustomAction': (dynamic instance) => instance.getCustomAction,
        r'requireObjects': (dynamic instance) => instance.requireObjects,
        r'requireObjectsList': (dynamic instance) =>
            instance.requireObjectsList,
        r'getBodyExtenstionParams': (dynamic instance) =>
            instance.getBodyExtenstionParams,
        r'getBodyCurrentActionASC': (dynamic instance) =>
            instance.getBodyCurrentActionASC,
        r'getBody': (dynamic instance) => instance.getBody,
        r'getHeadersExtenstion': (dynamic instance) =>
            instance.getHeadersExtenstion,
        r'getHeaders': (dynamic instance) => instance.getHeaders,
        r'getRespones': (dynamic instance) => instance.getRespones,
        r'viewCall': (dynamic instance) => instance.viewCall,
        r'addCall': (dynamic instance) => instance.addCall,
        r'listCall': (dynamic instance) => instance.listCall,
        r'getHttp': (dynamic instance) => instance.getHttp,
        r'getBodyCurrentAction': (dynamic instance) =>
            instance.getBodyCurrentAction
      },
      {r'iD=': (dynamic instance, value) => instance.iD = value},
      null,
      [
        const [1, 0, null],
        const [0, 0, null],
        const [
          0,
          0,
          const [#serverActions, #onResponse]
        ],
        const [
          1,
          0,
          const [#onResponse]
        ],
        const [
          2,
          0,
          const [#onResponse]
        ]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
